### ISSUE TITLE
No such module 'libtesseract'.

### ISSUE THREAD

**Issue by mixo44** [SwiftyTesseract/SwiftyTesseract#93] opened 2021-05-05 16:30 UTC
### Checklist
- [x] I've read the [Readme](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/README.md)
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).
- [x] I'm using Swift Package Manager 5.4 for dependency management

**Describe the bug**
Hello. I'm using your package as dependency for my swift package. During the archiving process of my package XCode throws this error:
*No such module 'libtesseract'*
`/Users/***/Library/Developer/Xcode/DerivedData/AppName-ekitcwqrzdfwtpeostylpkgaizdj/SourcePackages/checkouts/SwiftyTesseract/Sources/SwiftyTesseract/Tesseract+ConfigurationBuilder.swift:9:8: No such module 'libtesseract'`

I removed the derived data and cleaned the project but got same result. 
Can you help me please?

**Versions**
* Xcode: Version 12.5 (12E262)
* Swift: 5.4
* iOS: >= 12
* SwiftyTesseract: 4.0.1

**Additional context**
Swift package file:
```
// swift-tools-version:5.4
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Verifie",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(name: "AppName", targets: ["AppName"]),
    ],
    dependencies: [
        .package(url: "https://github.com/SwiftyTesseract/SwiftyTesseract.git", .upToNextMajor(from: "4.0.0"))
    ],
    targets: [
        .target(
            name: "AppName",
            dependencies: [
                .product(name: "SwiftyTesseract", package: "SwiftyTesseract")
            ],
            resources: [
                .copy("Resources/tessdata")
            ])
    ]
)
```

**Comment by Steven0351** [comment] 2021-05-05 18:22
What part of your build process are you performing the action outlined here: https://github.com/SwiftyTesseract/SwiftyTesseract#known-issue-submitting-to-app-store-connect. The only thing I can think of that would cause this issue is that you may be doing that too early?

**Comment by jb-apps** [comment] 2021-05-06 12:20
I am facing this problem since I updated to Xcode 12.5. I added the post-action, clean derived data (even deleted the folder), same problem.

**Comment by Steven0351** [comment] 2021-05-06 15:07
I'm unable to reproduce this. Here's what I've done:
1. Created a fresh project in Xcode 12.5
2. Created a local swift package that uses SwiftyTesseract as a dependency
3. Added some trivial code to use SwiftyTesseract in the package.
4. Added the local swift package as a library to the application target
5. Built, archived, and exported

I'm not getting any 'libtesseract' not found error when performing the above steps. If you could provide exact reproduction steps or provide a link to a minimal example repo that reproduces the issue it would be greatly appreciated.

**Comment by jb-apps** [comment] 2021-05-06 18:31
Thanks for the quick response @Steven0351 I can confirm it works now. 
I followed your steps and successfully archived a dummy project.

What I did in the main project was to totally reinstall SwiftyTesseract and it successfully archived it after. I guess it was a problem in SPM.

Thanks for the amazing work!

**Comment by Steven0351** [comment] 2021-05-06 18:38
Awesome, I'm glad you got it figured out! I also noticed that when doing this that when your application target doesn't directly depend on SwiftyTesseract, you don't even need the post-build step. So in your case, since you're depending on SwiftyTesseract in a separate Swift package, it's being statically linked and built into your Swift package and libtesseract.framework is never copied anywhere. I went looking through the application bundle and didn't find any libtesseract.framework bundled at all. Probably a weird discrepancy between the SPM build process and the xcodebuild build process.

**Comment by Steven0351** [comment] 2021-05-06 18:39
Going to close this for now, but I'm glad you got everything figured out

**Comment by Steven0351** [comment] 2021-05-06 22:20
Whoops I got a little carried away there @mixo44, I was thinking jb-apps was the original author of the issue when I closed this. I'm assuming in your bug report you're referring to https://github.com/verifie-global/verifie-iOS-spm as the SPM project. Would I be able to reproduce this issue with your Example project?

**Closed as completed** 2021-06-16 21:54 UTC
Labels: wontfix
